### ISSUE TITLE
Parties collection empty if no subscription in 9.9

### ISSUE THREAD

**Issue by thomasvalera** [Urigo/meteor-angular-socially#104]
In step 9.9 is written:

> Also, let's add a subscription to the parties in this Component as well, in case we will laod the app directly from this Component before loading the parties-list Component:

Which indicates that if the user accesses the details page via the list, no subscription is needed as the collection is already in the minimongo. 
Yet when commenting the subscription of step 9.9 out and accessing the details page via the list, the logging of the collection returns an empty array. How is that possible?

**Comment by kamilkisiela** [comment]
There is a new tutorial now. Please reopen if necessary :)
