### ISSUE TITLE
Does not work in 1.3

### ISSUE THREAD

**Issue by trajano** [Urigo/meteor-angular-socially#105]
After cloning the repository, I ran `meteor update` then ran `meteor` after the upgrade finished.

The following log message appears:

<pre>
Unable to resolve some modules:

  "angular" in /C/Users/Archimedes/AppData/Local/.meteor/packages/dotansimha_accounts-ui-angular/0.0.4/web.browser/accounts-ui-angular.js (web.browser)
  "underscore" in /C/Users/Archimedes/AppData/Local/.meteor/packages/angular-meteor-data/1.3.9/web.browser/.npm/package/node_modules/angular-meteor/dist/angular-meteor.js (web.browser)
  "jsondiffpatch" in /C/Users/Archimedes/AppData/Local/.meteor/packages/angular-meteor-data/1.3.9/web.browser/.npm/package/node_modules/angular-meteor/dist/angular-meteor.js (web.browser)

Consider running: meteor npm install --save angular underscore jsondiffpatch
</pre>

As noted, I have ran `meteor npm install --save angular underscore jsondiffpatch` once done, running `meteor` started cleaner.  However when accessing from the browser I receive the following message

<pre>
angular_angular.js?hash=c17a5a9…:83 Uncaught Error: [$injector:modulerr] Failed to instantiate module socially due to:
Error: [$injector:modulerr] Failed to instantiate module angular-meteor due to:
Error: [$injector:nomod] Module 'angular-meteor' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.8/$injector/nomod?p0=angular-meteor
    at http://localhost:3000/packages/angular_angular.js?hash=c17a5a9bc4ab8702438c39d764efe4d6334a23e2:83:12
</pre>

**Comment by trajano** [comment]
This may be related to https://github.com/Urigo/angular-meteor/issues/829#issuecomment-202711794

**Comment by Urigo** [comment]
@trajano should be fixed with the new `1.3.9_1` version.
Please let me know if that helped

**Comment by trajano** [comment]
Thanks I just tried it no runtime errors anymore, though it is my first time running the socially app, I guess it does not work on Windows well, there's a few UI issues.  For example on the register page on Firefox the form content is below the form itself works better on Chrome but still has a few rendering issues.  I had some issues with my own app last night in that the `ng-click` events are no longer being handled in my ui-router, I haven't checked up on it yet though.

![capture](https://cloud.githubusercontent.com/assets/110627/14109152/c1065c98-f58e-11e5-9c6a-598d243b3f7d.PNG)

If you can confirm that these issues are expected on Windows I guess I can close this.

**Comment by Urigo** [comment]
can you try running Socially after step 16, before the angular-material chapter?

**Comment by trajano** [comment]
Works well with tag `step_16` thanks.  Do you want to keep this open or just close it for now?

**Comment by Urigo** [comment]
I think we can close this.
thank you
