### ISSUE TITLE
TypeError: window.module is not a function

### ISSUE THREAD

**Issue by wayofme** [Urigo/meteor-angular-socially#106]
jasmine-client Fail at step04-step22.
step22:fails information
PartiesList.controller
should have perPage that equals 3 by default    Fail
TypeError: window.module is not a function
app/app.js?hash=a727701dd3b3a071fc8909c19afa35813ddc49ae:26:12: TypeError: window.module is not a function
should have page that equals 1 by default   Fail
TypeError: window.module is not a function
app/app.js?hash=a727701dd3b3a071fc8909c19afa35813ddc49ae:26:12: TypeError: window.module is not a function
should sort by name - ASC   Fail
TypeError: window.module is not a function
app/app.js?hash=a727701dd3b3a071fc8909c19afa35813ddc49ae:26:12: TypeError: window.module is not a function
should be able to change sorting    Fail
TypeError: window.module is not a function
app/app.js?hash=a727701dd3b3a071fc8909c19afa35813ddc49ae:26:12: TypeError: window.module is not a function
should be able to change page   Fail
TypeError: window.module is not a function
app/app.js?hash=a727701dd3b3a071fc8909c19afa35813ddc49ae:26:12: TypeError: window.module is not a function
PartiesSort.controller
should set property Fail
TypeError: window.module is not a function
app/app.js?hash=a727701dd3b3a071fc8909c19afa35813ddc49ae:315:12: TypeError: window.module is not a function
should set order    Fail
TypeError: window.module is not a function
app/app.js?hash=a727701dd3b3a071fc8909c19afa35813ddc49ae:315:12: TypeError: window.module is not a function
should set onChange Fail
TypeError: window.module is not a function
app/app.js?hash=a727701dd3b3a071fc8909c19afa35813ddc49ae:315:12: TypeError: window.module is not a function
PartiesSort.controller.changed()
should call onChange expression Fail
TypeError: window.module is not a function
app/app.js?hash=a727701dd3b3a071fc8909c19afa35813ddc49ae:315:12: TypeError: window.module is not a function
PartyAdd.controller.reset()
should clean up party object    Fail
TypeError: window.module is not a function
app/app.js?hash=a727701dd3b3a071fc8909c19afa35813ddc49ae:459:12: TypeError: window.module is not a function
PartyAdd.controller.submit()
should insert a new party   Fail
TypeError: window.module is not a function
app/app.js?hash=a727701dd3b3a071fc8909c19afa35813ddc49ae:459:12: TypeError: window.module is not a function
should call reset() Fail
TypeError: window.module is not a function
app/app.js?hash=a727701dd3b3a071fc8909c19afa35813ddc49ae:459:12: TypeError: window.module is not a function
PartyCreator.controller
should return an empty string if there is no party  Fail
TypeError: window.module is not a function
app/app.js?hash=a727701dd3b3a071fc8909c19afa35813ddc49ae:615:12: TypeError: window.module is not a function
should say `me` if logged in is the owner   Fail
TypeError: window.module is not a function
app/app.js?hash=a727701dd3b3a071fc8909c19afa35813ddc49ae:615:12: TypeError: window.module is not a function
should say `nobody` if user does not exist  Fail
TypeError: window.module is not a function
app/app.js?hash=a727701dd3b3a071fc8909c19afa35813ddc49ae:615:12: TypeError: window.module is not a function
should return user data if user exists and it is not logged one Fail
TypeError: window.module is not a function
app/app.js?hash=a727701dd3b3a071fc8909c19afa35813ddc49ae:615:12: TypeError: window.module is not a function
PartyDetails.controller.save()
should update a proper party    Fail
TypeError: window.module is not a function
app/app.js?hash=a727701dd3b3a071fc8909c19afa35813ddc49ae:794:12: TypeError: window.module is not a function
should update with proper modifier  Fail
TypeError: window.module is not a function
app/app.js?hash=a727701dd3b3a071fc8909c19afa35813ddc49ae:794:12: TypeError: window.module is not a function
PartyRemove.controller.remove()
should remove a party   Fail
TypeError: window.module is not a function
app/app.js?hash=a727701dd3b3a071fc8909c19afa35813ddc49ae:1111:12: TypeError: window.module is not a function

**Comment by kamilkisiela** [comment]
https://github.com/xolvio/meteor-jasmine/issues/332
https://github.com/Urigo/angular-meteor-docs/issues/37

**Comment by kamilkisiela** [comment]
@wayofme My PR [has been merged](https://github.com/xolvio/meteor-jasmine/commit/8f03aa1522a29ac55a507dd0635be7743817dffd) so you can use now 1.0.1 version.

**Comment by saulide** [comment]
Bug is reproducible with sanjo:jasmine@1.0.1
