### ISSUE TITLE
'$stateChangeError' event on 8.11 is never received

### ISSUE THREAD

**Issue by nikrabaev** [Urigo/meteor-angular-socially#108]
As I found out that's because of `"angular-ui-router": "^1.0.0-alpha.4"`. 
Changing it to `"angular-ui-router": "^0.2.18"` fixed the issue.

**Comment by kamilkisiela** [comment]
As you can see [here](https://github.com/angular-ui/ui-router/blob/master/src/ng1/stateEvents.ts#L1-L18), the state events have been deprecated.

To make those events work in apps with `angular-ui-router@1.0.0` you can always use [`$stateEvents.enable`](https://github.com/angular-ui/ui-router/blob/master/src/ng1/stateEvents.ts#L235-L243).

---

But I will just make Socially to use the latest stable version which is `0.2.18`. Give me few minutes to update tutorial ;)

**Comment by kamilkisiela** [comment]
@inberware Urigo/angular-meteor-docs#75 should fix it
