### ISSUE TITLE
step22. didn't work page scroll after import ionic.css on socially.js

### ISSUE THREAD

**Issue by kevin0858** [Urigo/meteor-angular-socially#111]
when i follow angular-meteor tutotial's socially app,
i could do everything before 'step22-ionic'.
but, during proceed step22, socially app didn't work scroll partiesList page.
i could found the problem when i proceed step by step.
the problem is step22.5(import 'ionic-sdk/release/css/ionic.css')
after imported ionic.css into socially.js, partiesList couldn't scrolling.
how can i fix it?

**Comment by DAB0mB** [comment]
@kevin0858 Thank you for the issue report. The issue is now no more
