### ISSUE TITLE
Small bug at productsSort component

### ISSUE THREAD

**Issue by finfort** [Urigo/meteor-angular-socially#113]
In this component
https://github.com/Urigo/meteor-angular-socially/blob/b93e344ebff255f6a01bbd18b68b66db5a454f83/imports/ui/components/partiesSort/partiesSort.js
importing template didn't work like this, `template` so it should be like this
`templateUrl: `imports/ui/components/${name}/${name}.html``
didn't know reason, but it help's me

**Comment by kamilkisiela** [comment]
It depends on what html compiler do you use.

If it's `urigo:static-templates`:

```
import template from './bla.html'; // outputs: <div> ...
```

If `angular-templates`:

```
import templateUrl from './bla.html'; // outputs: imports/.../bla.html
```

In the current Socially we're using `urigo:static-templates`
