### ISSUE TITLE
how to use md-tabs in angular-meteor

### ISSUE THREAD

**Issue by kevin0858** [Urigo/meteor-angular-socially#114]
i want to use md-tabs in my project.
when i tried to use md-tabs, it's ok to show tabs.
but, it didn't work when i clicked some tab. 
i had 3 tabs, clicked Tab2 and then it's not change from Tab1 to Tab2.
how can i do?

**Comment by nigelpasco** [comment]
Have a look at the code from the angular-material website. They have working examples of this, with code shown.

**Comment by DAB0mB** [comment]
@kevin0858 This is not an issue related to Socially, and I suggest you submit it here http://stackoverflow.com/questions/tagged/material-design where the community is bigger and it is more relevant
