### ISSUE TITLE
No update on the page when removing mongodb-document by using the terminal

### ISSUE THREAD

**Issue by phguen** [Urigo/meteor-angular-socially#12]
Hey together, im new to angular, meteor and mongo-db, so excuse my question.
I'm on step 3 of the tutorial and inserted a document using the mongo terminal, everythings ok, the page changes automatically and shows the new entry, thas pretty cool. But when I remove the same document using the terminal, I have to use F5 to reload the page to see the changes. Hope you can help me with this. I also hope this is the right place to ask this question, if not please tell me

**Comment by Urigo** [comment]
thank you so reporting @philonaut 
can you share the versions file so I'll see what versions of the packages are you running?

**Comment by phguen** [comment]
https://github.com/philonaut/socially/blob/master/versions

**Comment by Urigo** [comment]
looks like everything is updated.
I will check it out soon, sorry for that

**Comment by Urigo** [comment]
deleting from the code work ok right?

**Comment by Urigo** [comment]
@philonaut strange... I've just tested it and it works for me in step 3..

**Comment by phguen** [comment]
very strange, I'll try it again... and yes, deleting from the code works ok

**Comment by Urigo** [comment]
ok found the problem
fixing now

**Comment by Urigo** [comment]
Fixed in 0.7.1
Run 

```
meteor update
```

in console and check again please.

I'll update the tutorial's dependency after Meteor's new version will be out (likely later today)

**Comment by phguen** [comment]
Yes, it works :-) thx
