### ISSUE TITLE
Older version of socially tutorial (for Meteor 1.2)

### ISSUE THREAD

**Issue by aadadey** [Urigo/meteor-angular-socially#122]
Hi, I was wondering where I could find the previous version of the Socially App tutorial, the one that is compatible with Meteor version 1.2. Is there any way to access it? Thanks.

**Comment by Urigo** [comment]
You can get the code from this branch - https://github.com/Urigo/meteor-angular-socially/tree/1.2
and if you go back to the history of the main angular-meteor repo, you should be able to find a version of the website there.
Let me know if that worked for you
