### ISSUE TITLE
Unclear text in step 0.8 (angular1)

### ISSUE THREAD

**Issue by malaire** [Urigo/meteor-angular-socially#124]
Meaning of following text is unclear:

> It's very important to note - the paths are always absolute, not relative! so if main.html was inside a root folder of your app, you would have to place the whole path from the route app, doesn't matter where you're calling the file from.
> 
> E.g. if main.html was in a root folder your include would look like:
> <div ng-include="'main.html'"></div>

What is "route app", first time mentioned here?
Why is it said that files in root folder needs whole path, but following example shows no path?

**Comment by nigelpasco** [comment]
Hi,
The "route app" refers to the "route folder of the app" - maybe a bit clearer written in full.
See the example above this paragraph, where the ng-include uses the full path <div ng-include src="'client/main.html'"></div>, even though the code is already in the "client/" folder.
It is true that is client/main.html was in the root, you would use <...ng-include="'main.html">, and not <...ng-include="../main.html">.

Another example would be if you wanted to include folder "imports/ui/components/test.html", where you would use <div ng-include="'imports/ui/components/test.html'"> from within any other file.

I hope that makes sense.

**Comment by malaire** [comment]
Do you mean "root folder" or are you referring to Routes[1] which I've not yet learned?

[1] https://guide.meteor.com/routing.html

**Comment by nigelpasco** [comment]
root folder. That is , the folder 'my app' or whatever you called your application.

**Comment by DAB0mB** [comment]
@malaire Your'e right. Our instructions can be sometimes very unclear. Thank you submitting this issue and we're working and improving to get it right.
