### ISSUE TITLE
Tutorial failing at Step 1

### ISSUE THREAD

**Issue by nigelpasco** [Urigo/meteor-angular-socially#126]
Current version of Meteor (1.3.4.4), tutorial is currently not allowing tutorial to run without angular-templates.

At completion of step 1 of the tutorial, I get a blank page and the following error in console...

Error: [angular-meteor][err][404] client/main.html - HTML template does not exists! You can disable this error by following this guide http://www.angular-meteor.com/api/1.3.11/templates ...

**Comment by edubarbieri** [comment]
I'm having the same problem, any suggestions?

**Comment by kamilkisiela** [comment]
It should be fixed with new release of `angular-templates` Urigo/angular-meteor#1398

I'll update also Socially soon.

**Comment by Urigo** [comment]
was released.
Please @mention me if it's not fixed

**Comment by kamilkisiela** [comment]
@nigelpasco @edubarbieri Socially 1.0 has been updated. The docs are waiting to be deployed.

**Comment by Urigo** [comment]
deployed
