### ISSUE TITLE
Databinding: declare collection has wrong path

### ISSUE THREAD

**Issue by nguyenjk** [Urigo/meteor-angular-socially#127]
hi, 

while reading this http://www.angular-meteor.com/tutorials/socially/angular2/3-way-data-binding
I found that the path for declare collection is not consistent with the path that is being used below 

this is the path that is in declare collection section: both/collections/parties/parties.collection.ts
this is the path that is in app.component.ts: both/collections/parties.collection.

thank for making this tutorial available.

**Comment by DAB0mB** [comment]
@nguyenjk Thank you for submitting this issue. There are two versions of Socially, one is based on angular1 (aka socially1) and the second is based on angular2 (aka socially2). The issue you submitted belongs to socially2, whose issues page can be found [here](https://github.com/Urigo/meteor-angular2.0-socially). Regardless, I think the issue doesn't exist anymore :-)
