### ISSUE TITLE
Google Map didn't load at 16.10

### ISSUE THREAD

**Issue by TaymozL** [Urigo/meteor-angular-socially#130]
The google map didn't load correctly in PartyDetails page at 16.10. 
Says "Google Maps API Error : MissingKeyMapError " in console and the map in page goes "Oops! Something went wrong. This page didn't load Google Maps correctly. See the JavaScript console for technical details."

Displays well after adding PartiesMap in main page at end of step 16.

**Comment by BrianPhilips** [comment]
Google now requires you to have an API key to make requests.

To fix this error include the following tag inside the head section in client/Index.html

`<script src="https://maps.googleapis.com/maps/api/js?key=yourKEYhere"></script>`

Get your key here: [GoogleApiKey Generation site](https://developers.google.com/maps/documentation/javascript/get-api-key)

**Comment by DAB0mB** [comment]
@TaymozL Thank you for the issue @BrianPhilips Thank you very much for the solution, I am now adding a new step and hopefully the documentation will be updated asap.
