### ISSUE TITLE
file system copy issue -- step 20

### ISSUE THREAD

**Issue by TaymozL** [Urigo/meteor-angular-socially#132]
It seems that package 
jalik:ufs
support [copy] from one store to another only for Local fs with 
jalik:ufs-local
while 
jalik:ufs-gridfs
seems not work.

And to use npm "gm", one should first install
imagemagick

**Comment by DAB0mB** [comment]
@TaymozL It's already noted in right after step 20.6 that you should make sure that either GraphicsMagick or ImageMagick is installed. About the GridFS issue, how did you run to the conclusion that it doesn't work?

**Comment by DAB0mB** [comment]
@TaymozL I fixed those issues, hopefully will be deployed today
