### ISSUE TITLE
Erroneous file reference at "Step 2 - Dynamic Template"

### ISSUE THREAD

**Issue by oviniciusfeitosa** [Urigo/meteor-angular-socially#135]
Hello!

I think the correct file reference for this section below is "main.js", instead "app.js"

```
The ngController directive, located on the div tag, references the name of our controller, PartiesListCtrl (located in the JavaScript file **app.js**).
```

I found it [here](http://www.angular-meteor.com/tutorials/socially/angular1/dynamic-template) .

:+1:

**Comment by DAB0mB** [comment]
@vinnyfs89 Thank you very much this will be soon merged to the master branch of our documentation site :-)
