### ISSUE TITLE
can't get party creator in "Step 13 - Using and creating AngularJS filters"

### ISSUE THREAD

**Issue by mhs-mlkn** [Urigo/meteor-angular-socially#136]
Hi
the PartyCreator component added in step 13 always return `nobody` as owner's username and `Meteor.users.findOne(owner)`
always return undefined. i also grab and run example code from tutorial's link on github and still doesn't work!!!
would you please tell me what's wrong with the code?
tutorial sample code link: [https://github.com/Urigo/meteor-angular-socially/archive/step_13.zip]

**Comment by ghost** [comment]
I got the same issue

Did you manage to solve it ?

**Comment by Urigo** [comment]
fixed and deployed
