### ISSUE TITLE
How to install the master branch

### ISSUE THREAD

**Issue by barak-haviv** [Urigo/meteor-angular-socially#139]
I did clone and than run meteor but it didn't work.
Is there more instructions ?

**Comment by DAB0mB** [comment]
@barak-haviv You simply type

```
$ npm install
```

and then

```
$ meteor run
```

As for now there is a problem with the final step 23 we're working on fixing it, as for now try to checkout step 22 and work from there, a fix will be available soon

**Comment by Urigo** [comment]
@barak-haviv we've updated the last chapter, can you please check again with the latest master branch?

**Comment by Urigo** [comment]
that should work now.
@barak-haviv please open a new issue if I'm wrong, thanks!
