### ISSUE TITLE
currentUser reference in template (step_08)

### ISSUE THREAD

**Issue by okosokolovo** [Urigo/meteor-angular-socially#14]
When adding newParty item via form in _parties-list.ng.html_ template, isn't it right to write the first statement in ng-click simply like `newParty.owner=currentUser._id;` ?

I have tried it and it works good. Also checking with chrome dev tools as if confirms the case of inheritance as described in AngularJS docs under the section [Scope Hierarchies](https://docs.angularjs.org/guide/scope), so imho no need to mix with _$root_ in html template code ?

**Comment by Urigo** [comment]
@okosokolovo that's a good idea, but as this is a tutorial I would rather leave it like that so that people will understand better exactly where currentUser is coming from...
