### ISSUE TITLE
issue running meteor project 

### ISSUE THREAD

**Issue by jeffchiu605** [Urigo/meteor-angular-socially#142]
Hi. I'm trying to run Meteor w/angular flavor, but when i try to install angular project, processing 'stalls' in loop .

I have troubled running angular-meteor at my environment.
I git clone the project from https://github.com/Urigo/meteor-angular-socially

When reporting a bug, please be sure to include the following:

 I'm running Meteor 1.4.1.3. version of angular-meteor 
mongo upgraded from 1.1.12_5 to 1.1.13
npm-mongo upgraded from 2.2.10_1 to 2.2.11_1
meteor-angular-socially-master: updated to Meteor 1.4.1.3.

 What packages or other dependencies I'm using

The behavior you expect to see, and the actual behavior
I expected angular-meteor to run, and it shows localhost:3000 but it does not show me anything after that.

Unable to resolve some modules:

```

master/@angular
npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/jchiu/.meteor/packages/meteor-tool/.1.4.2.zi1w5b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node" "/Users/jchiu/.meteor/packages/meteor-tool/.1.4.2.zi1w5b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "install" "--save" "@angular" "spawn-sync"
npm ERR! node v4.6.1
npm ERR! npm  v3.10.9
npm ERR! path /Users/jchiu/Downloads/meteor-angular-socially-master/@angular
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/Users/jchiu/Downloads/meteor-angular-socially-master/@angular'
npm ERR! enoent ENOENT: no such file or directory, open '/Users/jchiu/Downloads/meteor-angular-socially-master/@angular'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
```

Here's the output from terminal:

```
W20161027-12:01:55.844(-7)?` (STDERR) ufs: permissions are not defined for store "thumbs"
W20161027-12:01:55.988(-7)? (STDERR) ufs: permissions are not defined for store "images"
=> Started your app.

=> App running at: http://localhost:3000/


```

➜  meteor-angular-socially-master git:(master) ✗ meteor run
[[[[[ ~/Downloads/meteor-angular-socially-master ]]]]]

=> Started proxy.
=> Started MongoDB.
imports/ui/components/auth/auth.ts (1, 26): Cannot find module 'angular'.
imports/ui/components/auth/auth.ts (2, 32): Cannot find module 'angular-meteor'.
imports/ui/components/auth/auth.ts (21, 10): Property 'helpers' does not exist on type 'Auth'.
imports/ui/components/login/login.ts (1, 26): Cannot find module 'angular'.
imports/ui/components/login/login.ts (2, 32): Cannot find module 'angular-meteor'.
imports/ui/components/login/login.ts (3, 27): Cannot find module 'angular-ui-router'.
imports/ui/components/login/login.ts (8, 8): Module '"imports/ui/components/login/web"' has no default export.
imports/ui/components/login/login.ts (10, 8): Module '"imports/ui/components/login/mobile"' has no default export.
imports/ui/components/login/mobile.ts (7, 10): Property '$state' does not exist on type 'Login'.
imports/ui/components/login/mobile.ts (11, 10): Property 'isStepTwo' does not exist on type 'Login'.
imports/ui/components/login/mobile.ts (12, 10): Property 'phoneNumber' does not exist on type 'Login'.
imports/ui/components/login/mobile.ts (13, 10): Property 'verificationCode' does not exist on type 'Login'.
imports/ui/components/login/mobile.ts (14, 10): Property 'error' does not exist on type 'Login'.
imports/ui/components/login/mobile.ts (18, 14): Property 'requestPhoneVerification' does not exist on type 'typeof Accounts'.
imports/ui/components/login/mobile.ts (18, 44): Property 'phoneNumber' does not exist on type 'Login'.
imports/ui/components/login/mobile.ts (18, 62): Property '$bindToContext' does not exist on type 'Login'.
imports/ui/components/login/mobile.ts (21, 14): Property 'error' does not exist on type 'Login'.
imports/ui/components/login/mobile.ts (23, 14): Property 'error' does not exist on type 'Login'.
imports/ui/components/login/mobile.ts (25, 14): Property 'isStepTwo' does not exist on type 'Login'.
imports/ui/components/login/mobile.ts (31, 14): Property 'verifyPhone' does not exist on type 'typeof Accounts'.
imports/ui/components/login/mobile.ts (31, 31): Property 'phoneNumber' does not exist on type 'Login'.
imports/ui/components/login/mobile.ts (31, 49): Property 'verificationCode' does not exist on type 'Login'.
imports/ui/components/login/mobile.ts (31, 72): Property '$bindToContext' does not exist on type 'Login'.
imports/ui/components/login/mobile.ts (33, 14): Property 'error' does not exist on type 'Login'.
imports/ui/components/login/mobile.ts (36, 14): Property '$state' does not exist on type 'Login'.
imports/ui/components/login/web.ts (7, 10): Property '$state' does not exist on type 'Login'.
imports/ui/components/login/web.ts (11, 10): Property 'credentials' does not exist on type 'Login'.
imports/ui/components/login/web.ts (16, 10): Property 'error' does not exist on type 'Login'.
imports/ui/components/login/web.ts (20, 35): Property 'credentials' does not exist on type 'Login'.
imports/ui/components/login/web.ts (20, 59): Property 'credentials' does not exist on type 'Login'.
imports/ui/components/login/web.ts (21, 12): Property '$bindToContext' does not exist on type 'Login'.
imports/ui/components/login/web.ts (23, 16): Property 'error' does not exist on type 'Login'.
imports/ui/components/login/web.ts (25, 16): Property '$state' does not exist on type 'Login'.
imports/ui/components/navigation/navigation.ts (1, 26): Cannot find module 'angular'.
imports/ui/components/navigation/navigation.ts (2, 32): Cannot find module 'angular-meteor'.
imports/ui/components/partiesList/partiesList.ts (1, 26): Cannot find module 'angular'.
imports/ui/components/partiesList/partiesList.ts (2, 32): Cannot find module 'angular-meteor'.
imports/ui/components/partiesList/partiesList.ts (3, 27): Cannot find module 'angular-ui-router'.
imports/ui/components/partiesList/partiesList.ts (4, 34): Cannot find module 'angular-utils-pagination'.
imports/ui/components/partiesList/partiesList.ts (6, 24): Cannot find module 'meteor/tmeasday:publish-counts'.
imports/ui/components/partiesList/partiesList.ts (27, 10): Property 'perPage' does not exist on type 'PartiesList'.
imports/ui/components/partiesList/partiesList.ts (28, 10): Property 'page' does not exist on type 'PartiesList'.
imports/ui/components/partiesList/partiesList.ts (29, 10): Property 'sort' does not exist on type 'PartiesList'.
imports/ui/components/partiesList/partiesList.ts (32, 10): Property 'searchText' does not exist on type 'PartiesList'.
imports/ui/components/partiesList/partiesList.ts (34, 10): Property 'subscribe' does not exist on type 'PartiesList'.
imports/ui/components/partiesList/partiesList.ts (35, 30): Property 'perPage' does not exist on type 'PartiesList'.
imports/ui/components/partiesList/partiesList.ts (36, 24): Argument of type 'number' is not assignable to parameter of type 'string'.
imports/ui/components/partiesList/partiesList.ts (36, 30): Property 'getReactively' does not exist on type 'PartiesList'.
imports/ui/components/partiesList/partiesList.ts (36, 64): Property 'perPage' does not exist on type 'PartiesList'.
imports/ui/components/partiesList/partiesList.ts (37, 20): Property 'getReactively' does not exist on type 'PartiesList'.
imports/ui/components/partiesList/partiesList.ts (38, 15): Property 'getReactively' does not exist on type 'PartiesList'.
imports/ui/components/partiesList/partiesList.ts (41, 10): Property 'subscribe' does not exist on type 'PartiesList'.
imports/ui/components/partiesList/partiesList.ts (42, 10): Property 'subscribe' does not exist on type 'PartiesList'.
imports/ui/components/partiesList/partiesList.ts (44, 10): Property 'helpers' does not exist on type 'PartiesList'.
imports/ui/components/partiesList/partiesList.ts (63, 17): Property 'isLoggedIn' does not exist on type 'PartiesList'.
imports/ui/components/partiesList/partiesList.ts (63, 52): Property 'currentUserId' does not exist on type 'PartiesList'.
imports/ui/components/partiesList/partiesList.ts (67, 10): Property 'page' does not exist on type 'PartiesList'.
imports/ui/components/partiesList/partiesList.ts (71, 10): Property 'sort' does not exist on type 'PartiesList'.
imports/ui/components/partiesMap/partiesMap.ts (1, 26): Cannot find module 'angular'.
imports/ui/components/partiesMap/partiesMap.ts (2, 32): Cannot find module 'angular-meteor'.
imports/ui/components/partiesMap/partiesMap.ts (13, 10): Property 'map' does not exist on type 'PartiesMap'.
imports/ui/components/partiesSort/partiesSort.ts (1, 26): Cannot find module 'angular'.
imports/ui/components/partiesSort/partiesSort.ts (2, 32): Cannot find module 'angular-meteor'.
imports/ui/components/partiesSort/partiesSort.ts (12, 10): Property 'onChange' does not exist on type 'PartiesSort'.
imports/ui/components/partiesSort/partiesSort.ts (14, 15): Property 'property' does not exist on type 'PartiesSort'.
imports/ui/components/partiesSort/partiesSort.ts (14, 40): Property 'order' does not exist on type 'PartiesSort'.
imports/ui/components/partyAdd/partyAdd.ts (1, 26): Cannot find module 'angular'.
imports/ui/components/partyAdd/partyAdd.ts (2, 32): Cannot find module 'angular-meteor'.
imports/ui/components/partyAdd/partyAdd.ts (12, 10): Property 'party' does not exist on type 'PartyAdd'.
imports/ui/components/partyAdd/partyAdd.ts (16, 10): Property 'party' does not exist on type 'PartyAdd'.
imports/ui/components/partyAdd/partyAdd.ts (17, 25): Property 'party' does not exist on type 'PartyAdd'.
imports/ui/components/partyAdd/partyAdd.ts (19, 13): Property 'done' does not exist on type 'PartyAdd'.
imports/ui/components/partyAdd/partyAdd.ts (20, 12): Property 'done' does not exist on type 'PartyAdd'.
imports/ui/components/partyAdd/partyAdd.ts (27, 10): Property 'party' does not exist on type 'PartyAdd'.
imports/ui/components/partyAddButton/partyAddButton.ts (1, 26): Cannot find module 'angular'.
imports/ui/components/partyAddButton/partyAddButton.ts (2, 32): Cannot find module 'angular-meteor'.
imports/ui/components/partyAddButton/partyAddButton.ts (12, 10): Property '$mdDialog' does not exist on type 'PartyAddButton'.
imports/ui/components/partyAddButton/partyAddButton.ts (13, 10): Property '$mdMedia' does not exist on type 'PartyAddButton'.
imports/ui/components/partyAddButton/partyAddButton.ts (17, 10): Property '$mdDialog' does not exist on type 'PartyAddButton'.
imports/ui/components/partyAddButton/partyAddButton.ts (30, 24): Property '$mdMedia' does not exist on type 'PartyAddButton'.
imports/ui/components/partyAddButton/partyAddButton.ts (30, 47): Property '$mdMedia' does not exist on type 'PartyAddButton'.
imports/ui/components/partyCreator/partyCreator.ts (1, 26): Cannot find module 'angular'.
imports/ui/components/partyCreator/partyCreator.ts (2, 32): Cannot find module 'angular-meteor'.
imports/ui/components/partyCreator/partyCreator.ts (18, 10): Property 'subscribe' does not exist on type 'PartyCreator'.
imports/ui/components/partyCreator/partyCreator.ts (20, 10): Property 'helpers' does not exist on type 'PartyCreator'.
imports/ui/components/partyDetails/partyDetails.ts (1, 26): Cannot find module 'angular'.
imports/ui/components/partyDetails/partyDetails.ts (2, 32): Cannot find module 'angular-meteor'.
imports/ui/components/partyDetails/partyDetails.ts (3, 27): Cannot find module 'angular-ui-router'.
imports/ui/components/partyDetails/partyDetails.ts (36, 12): Property 'isOwner' does not exist on type 'PartyDetails'.
imports/ui/components/partyDetails/partyDetails.ts (36, 47): Property 'owner' does not exist on type 'Object'.
imports/ui/components/partyDetails/partyDetails.ts (45, 24): Property 'public' does not exist on type 'Object'.
imports/ui/components/partyDetails/partyDetails.ts (45, 45): Property 'owner' does not exist on type 'Object'.
imports/ui/components/partyDetails/partyDetails.ts (50, 23): Property '_id' does not exist on type 'Object'.
imports/ui/components/partyDetails/partyDetails.ts (53, 26): Property 'name' does not exist on type 'Object'.
imports/ui/components/partyDetails/partyDetails.ts (54, 33): Property 'description' does not exist on type 'Object'.
imports/ui/components/partyDetails/partyDetails.ts (55, 28): Property 'public' does not exist on type 'Object'.
imports/ui/components/partyDetails/partyDetails.ts (56, 30): Property 'location' does not exist on type 'Object'.
imports/ui/components/partyImage/partyImage.ts (1, 26): Cannot find module 'angular'.
imports/ui/components/partyImage/partyImage.ts (2, 32): Cannot find module 'angular-meteor'.
imports/ui/components/partyImage/partyImage.ts (13, 10): Property 'helpers' does not exist on type 'PartyImage'.
imports/ui/components/partyMap/partyMap.ts (1, 26): Cannot find module 'angular'.
imports/ui/components/partyMap/partyMap.ts (2, 32): Cannot find module 'angular-meteor'.
imports/ui/components/partyMap/partyMap.ts (12, 10): Property 'map' does not exist on type 'PartyMap'.
imports/ui/components/partyMap/partyMap.ts (26, 10): Property 'marker' does not exist on type 'PartyMap'.
imports/ui/components/partyMap/partyMap.ts (40, 10): Property 'location' does not exist on type 'PartyMap'.
imports/ui/components/partyRemove/partyRemove.ts (1, 26): Cannot find module 'angular'.
imports/ui/components/partyRemove/partyRemove.ts (2, 32): Cannot find module 'angular-meteor'.
imports/ui/components/partyRemove/partyRemove.ts (9, 14): Property 'party' does not exist on type 'PartyRemove'.
imports/ui/components/partyRemove/partyRemove.ts (10, 27): Property 'party' does not exist on type 'PartyRemove'.
imports/ui/components/partyRsvp/partyRsvp.ts (1, 26): Cannot find module 'angular'.
imports/ui/components/partyRsvp/partyRsvp.ts (2, 32): Cannot find module 'angular-meteor'.
imports/ui/components/partyRsvp/partyRsvp.ts (3, 20): Cannot find module 'underscore'.
imports/ui/components/partyRsvp/partyRsvp.ts (32, 30): Property 'party' does not exist on type 'PartyRsvp'.
imports/ui/components/partyRsvp/partyRsvp.ts (41, 13): Property 'party' does not exist on type 'PartyRsvp'.
imports/ui/components/partyRsvp/partyRsvp.ts (42, 33): Property 'party' does not exist on type 'PartyRsvp'.
imports/ui/components/partyRsvpsList/partyRsvpsList.ts (1, 26): Cannot find module 'angular'.
imports/ui/components/partyRsvpsList/partyRsvpsList.ts (2, 32): Cannot find module 'angular-meteor'.
imports/ui/components/partyUninvited/partyUninvited.ts (19, 12): Property 'users' does not exist on type 'PartyUninvited'.
imports/ui/components/partyUpload/partyUpload.ts (1, 26): Cannot find module 'angular'.
imports/ui/components/partyUpload/partyUpload.ts (2, 32): Cannot find module 'angular-meteor'.
imports/ui/components/partyUpload/partyUpload.ts (3, 31): Cannot find module 'ng-file-upload'.
imports/ui/components/partyUpload/partyUpload.ts (20, 10): Property 'uploaded' does not exist on type 'PartyUpload'.
imports/ui/components/partyUpload/partyUpload.ts (22, 10): Property 'subscribe' does not exist on type 'PartyUpload'.
imports/ui/components/partyUpload/partyUpload.ts (23, 12): Property 'getReactively' does not exist on type 'PartyUpload'.
imports/ui/components/partyUpload/partyUpload.ts (26, 10): Property 'helpers' does not exist on type 'PartyUpload'.
imports/ui/components/partyUpload/partyUpload.ts (40, 12): Property 'currentFile' does not exist on type 'PartyUpload'.
imports/ui/components/partyUpload/partyUpload.ts (44, 28): Property '$bindToContext' does not exist on type 'PartyUpload'.
imports/ui/components/partyUpload/partyUpload.ts (45, 14): Property 'cropImgSrc' does not exist on type 'PartyUpload'.
imports/ui/components/partyUpload/partyUpload.ts (46, 14): Property 'myCroppedImage' does not exist on type 'PartyUpload'.
imports/ui/components/partyUpload/partyUpload.ts (51, 12): Property 'cropImgSrc' does not exist on type 'PartyUpload'.
imports/ui/components/partyUpload/partyUpload.ts (56, 17): Property 'myCroppedImage' does not exist on type 'PartyUpload'.
imports/ui/components/partyUpload/partyUpload.ts (56, 38): Property 'currentFile' does not exist on type 'PartyUpload'.
imports/ui/components/partyUpload/partyUpload.ts (56, 61): Property '$bindToContext' does not exist on type 'PartyUpload'.
imports/ui/components/partyUpload/partyUpload.ts (57, 12): Property 'uploaded' does not exist on type 'PartyUpload'.
imports/ui/components/partyUpload/partyUpload.ts (59, 17): Property 'files' does not exist on type 'PartyUpload'.
imports/ui/components/partyUpload/partyUpload.ts (59, 32): Property 'files' does not exist on type 'PartyUpload'.
imports/ui/components/partyUpload/partyUpload.ts (60, 14): Property 'files' does not exist on type 'PartyUpload'.
imports/ui/components/partyUpload/partyUpload.ts (62, 12): Property 'files' does not exist on type 'PartyUpload'.
imports/ui/components/partyUpload/partyUpload.ts (71, 10): Property 'cropImgSrc' does not exist on type 'PartyUpload'.
imports/ui/components/partyUpload/partyUpload.ts (72, 10): Property 'myCroppedImage' does not exist on type 'PartyUpload'.
imports/ui/components/password/password.ts (1, 26): Cannot find module 'angular'.
imports/ui/components/password/password.ts (2, 32): Cannot find module 'angular-meteor'.
imports/ui/components/password/password.ts (3, 27): Cannot find module 'angular-ui-router'.
imports/ui/components/password/password.ts (13, 10): Property '$state' does not exist on type 'Register'.
imports/ui/components/password/password.ts (17, 10): Property 'credentials' does not exist on type 'Register'.
imports/ui/components/password/password.ts (21, 10): Property 'error' does not exist on type 'Register'.
imports/ui/components/password/password.ts (25, 34): Property 'credentials' does not exist on type 'Register'.
imports/ui/components/password/password.ts (25, 52): Property '$bindToContext' does not exist on type 'Register'.
imports/ui/components/password/password.ts (27, 14): Property 'error' does not exist on type 'Register'.
imports/ui/components/password/password.ts (29, 14): Property '$state' does not exist on type 'Register'.
imports/ui/components/register/register.ts (1, 26): Cannot find module 'angular'.
imports/ui/components/register/register.ts (2, 32): Cannot find module 'angular-meteor'.
imports/ui/components/register/register.ts (3, 27): Cannot find module 'angular-ui-router'.
imports/ui/components/register/register.ts (13, 10): Property '$state' does not exist on type 'Register'.
imports/ui/components/register/register.ts (17, 10): Property 'credentials' does not exist on type 'Register'.
imports/ui/components/register/register.ts (22, 10): Property 'error' does not exist on type 'Register'.
imports/ui/components/register/register.ts (26, 30): Property 'credentials' does not exist on type 'Register'.
imports/ui/components/register/register.ts (27, 12): Property '$bindToContext' does not exist on type 'Register'.
imports/ui/components/register/register.ts (29, 16): Property 'error' does not exist on type 'Register'.
imports/ui/components/register/register.ts (31, 16): Property '$state' does not exist on type 'Register'.
imports/ui/components/socially/socially.ts (1, 26): Cannot find module 'angular'.
imports/ui/components/socially/socially.ts (2, 32): Cannot find module 'angular-meteor'.
imports/ui/components/socially/socially.ts (3, 29): Cannot find module 'angular-material'.
imports/ui/components/socially/socially.ts (4, 29): Cannot find module 'angular-sanitize'.
imports/ui/components/socially/socially.ts (5, 27): Cannot find module 'angular-ui-router'.
imports/api/images/helpers.ts (44, 23): Property 'result' does not exist on type 'EventTarget'.
imports/api/images/methods.ts (1, 26): Cannot find module 'meteor/jalik:ufs'.
imports/api/images/methods.ts (16, 8): Property 'name' does not exist on type 'Blob'.
imports/api/images/methods.ts (19, 16): Cannot find name '_'.
imports/api/images/store.ts (1, 26): Cannot find module 'meteor/jalik:ufs'.
imports/api/parties/collection.ts (7, 28): Property 'owner' does not exist on type '{}'.
imports/api/parties/collection.ts (10, 28): Property 'owner' does not exist on type '{}'.
imports/api/parties/collection.ts (13, 28): Property 'owner' does not exist on type '{}'.
imports/api/parties/methods.ts (1, 20): Cannot find module 'underscore'.
imports/api/parties/methods.ts (32, 13): Property 'owner' does not exist on type '{}'.
imports/api/parties/methods.ts (36, 13): Property 'public' does not exist on type '{}'.
imports/api/parties/methods.ts (40, 24): Property 'owner' does not exist on type '{}'.
imports/api/parties/methods.ts (40, 52): Property 'invited' does not exist on type '{}'.
imports/api/parties/methods.ts (55, 34): Property 'title' does not exist on type '{}'.
imports/api/parties/methods.ts (57, 46): Property 'title' does not exist on type '{}'.
imports/api/parties/methods.ts (113, 41): Property 'rsvps' does not exist on type '{}'.
imports/api/parties/publish.ts (2, 24): Cannot find module 'meteor/tmeasday:publish-counts'.
imports/api/parties/publish.ts (40, 16): Property 'name' does not exist on type '{ $or: ({ $and: ({ public: boolean; } | { public: { $exists: boolean; }; })[]; } | { $and: { owne...'.
imports/ui/filters/displayImageFilter.ts (1, 26): Cannot find module 'angular'.
imports/ui/filters/displayNameFilter.ts (1, 26): Cannot find module 'angular'.
imports/ui/filters/uninvitedFilter.ts (1, 26): Cannot find module 'angular'.
imports/ui/filters/uninvitedFilter.ts (2, 20): Cannot find module 'underscore'.
imports/ui/filters/uninvitedPipe.ts (2, 20): Cannot find module 'underscore'.
client/main.ts (2, 26): Cannot find module 'angular'.
client/main.ts (53, 1): Supplied parameters do not match any signature of call target.
client/main.ts (54, 1): Supplied parameters do not match any signature of call target.
client/main.ts (55, 1): Supplied parameters do not match any signature of call target.
client/main.ts (56, 1): Supplied parameters do not match any signature of call target.
client/main.ts (57, 1): Supplied parameters do not match any signature of call target.
client/main.ts (58, 1): Supplied parameters do not match any signature of call target.
client/main.ts (59, 1): Supplied parameters do not match any signature of call target.
client/main.ts (60, 1): Supplied parameters do not match any signature of call target.
client/main.ts (61, 1): Supplied parameters do not match any signature of call target.
client/main.ts (63, 1): Supplied parameters do not match any signature of call target.
client/main.ts (64, 1): Supplied parameters do not match any signature of call target.
client/main.ts (65, 1): Supplied parameters do not match any signature of call target.
client/main.ts (66, 1): Supplied parameters do not match any signature of call target.
client/main.ts (67, 1): Supplied parameters do not match any signature of call target.
client/main.ts (68, 1): Supplied parameters do not match any signature of call target.
client/main.ts (69, 1): Supplied parameters do not match any signature of call target.
client/main.ts (70, 1): Supplied parameters do not match any signature of call target.
client/main.ts (71, 1): Supplied parameters do not match any signature of call target.

Unable to resolve some modules:

  "@angular/http" in
/Users/jchiu/Downloads/meteor-angular-socially-master/node_modules/@angular/material/material.umd.js
(web.browser)
  "spawn-sync" in
/Users/jchiu/Downloads/meteor-angular-socially-master/node_modules/cross-spawn/index.js
(web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save @angular spawn-sync

W20161028-11:11:50.304(-7)? (STDERR) ufs: permissions are not defined for store "thumbs"
W20161028-11:11:50.461(-7)? (STDERR) ufs: permissions are not defined for store "images"
=> Started your app.

=> App running at: http://localhost:3000/``

```
```

**Comment by DAB0mB** [comment]
@jeffchiu605 From the paths presented in the above log I assume that your'e using Windows OS, it's an important information so be sure to note it in the future. You gave two pieces of information regarding complications with node modules which seem to conflict with each other so I'm quiet confused and I quote.

The first is:

---

Unable to resolve some modules

```
master/@angular
npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/jchiu/.meteor/packages/meteor-tool/.1.4.2.zi1w5b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node" "/Users/jchiu/.meteor/packages/meteor-tool/.1.4.2.zi1w5b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "install" "--save" "@angular" "spawn-sync"
npm ERR! node v4.6.1
npm ERR! npm  v3.10.9
npm ERR! path /Users/jchiu/Downloads/meteor-angular-socially-master/@angular
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/Users/jchiu/Downloads/meteor-angular-socially-master/@angular'
npm ERR! enoent ENOENT: no such file or directory, open '/Users/jchiu/Downloads/meteor-angular-socially-master/@angular'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
```

---

And the second is:

---

Unable to resolve some modules:

```
"@angular/http" in
/Users/jchiu/Downloads/meteor-angular-socially-master/node_modules/@angular/material/material.umd.js
(web.browser)
"spawn-sync" in
/Users/jchiu/Downloads/meteor-angular-socially-master/node_modules/cross-spawn/index.js
```

---

So which one of them did you encounter? Regardless, I will give you a solution for each one of the individually.

The first quote:

`npm` seems to look for modules in the wrong dir. In actuality it looks in `/Users/jchiu/Downloads/meteor-angular-socially-master/@angular` while it should be `/Users/jchiu/Downloads/meteor-angular-socially-master/node_modules/@angular`. Make sure you installed the modules correctly using the following command:

```
$ meteor npm install
```

And if you did, make sure your user PATH is set correctly. More information on how to change environment variables on Windows OS can be found [here](http://superuser.com/questions/165909/how-can-i-set-user-environmental-variables-such-as-path-from-a-non-administrat).

Second quote:

This error is caused for two reasons. The first one is because the package `@angular/material` relies on `@angular/http` and it doesn't require it one of its peer dependencies. I already took care of it in the following pull request https://github.com/angular/material2/pull/1579 and we're waiting for the next upcoming version so the fix will be official. As for now run the following:

```
$ meteor npm install @angular/http --save
```

The second error is caused your local `node` version is very old! It's probably v0.10.0 or lower, then again it's important to note all possible information. As you can see in the following piece of `spawn-cross` https://github.com/IndigoUnited/node-cross-spawn/blob/master/index.js#L34 you will need to run the following:

```
$ meteor npm install --save spawn-sync
```

Which is the obvious solution, but I'd recommend to just upgrade your node's version using [n](https://www.npmjs.com/package/n).

Hopefully this helps, would like to hear from you.

**Comment by jeffchiu605** [comment]
Thank you for the solution. 
My environment is actually OSX Sierra.
But I try some of your solution, and it seems to be working now.

**Comment by Urigo** [comment]
great

**Comment by aliig** [comment]
Thank you for the solution, @DAB0mB . Could you provide a bit more detail on the first solution? I used `meteor npm install`, but I'm encountering the same issue where npm is looking for modules in the wrong directory (it's omitting the `node_modules` subdirectory when looking for `@angular`). I'm running Windows and I'm familiar with changing PATH variables, but I'm not sure what needs to be changed to make this work properly. Thank you!
