### ISSUE TITLE
Missing Step 3 content for Meteor-Angular 1 Tutorial

### ISSUE THREAD

**Issue by Digital-Thor** [Urigo/meteor-angular-socially#143]
The step 3 page comes up blank if accessed directly:

https://www.angular-meteor.com/tutorials/socially/angular1/3-way-data-binding

Or inherits the content from the previous page if accessed through navigation buttons (prev/next).  Checked in both Chrome and FireFox on Windows 7/64bit.

For the first case above (blank page), Chrome console reports:

    Uncaught Error: Step 3.3: Multiple files in patch. 
    Must specify filename which is one of: client/main.js, server/main.js

**Comment by Digital-Thor** [comment]
Interestingly, the page is working fine today.

**Comment by DAB0mB** [comment]
@Digital-Thor You weren't wrong, it's just that I fixed it before noticing your issue haha.
