### ISSUE TITLE
step 3 - ng1 / partiesList.js - collection import missing?

### ISSUE THREAD

**Issue by anoff** [Urigo/meteor-angular-socially#144]
Just going through your tutorial and at step#3 the code won't run for me. 

```
modules.js?hash=d34111c…:14609 ReferenceError: Parties is not defined
```

Am I missing something? Adding `import { Parties } from '../../../../collections/parties';` to the [import statements](https://github.com/Urigo/meteor-angular-socially/blob/step_03/imports/ui/components/partiesList/partiesList.js#L4) fixes it. But all the relativity makes me 😷.

**Comment by GbalsaC** [comment]
Have the same issue on tutorial
