### ISSUE TITLE
PartiesSort not work (TypeError: this.onChange is not a function)

### ISSUE THREAD

**Issue by flawlite** [Urigo/meteor-angular-socially#147]
It works before, but I don't know why it fails now, even I take the tutorial again from the beginning.

**Comment by vsuhasm** [comment]
@flawlite how did you fix this?

**Comment by flawlite** [comment]
Just add $timeout (ref. from latest commit)

`class PartiesSort {
  constructor($timeout) {
    'ngInject';

    $timeout(() => this.changed());
  }

  changed() {
    this.onChange({
      sort: {
        [this.property]: parseInt(this.order)
      }
    });
  }
}`
