### ISSUE TITLE
ng-app is showing twice

### ISSUE THREAD

**Issue by Tallyb** [Urigo/meteor-angular-socially#19]
My index.html is as simple as: 

```
<head>
    <base href="/">
</head>
<body>
    <div ng-app="morffy">
        <div ui-view></div>
    </div>
</body>
```

when inspecting the result, the ng-app is showing twice. the first one has a ui-view div that  contains all the scripts. 
any idea?

**Comment by Urigo** [comment]
Can you please share the whole repo?

**Comment by Tallyb** [comment]
I think it because I had a bower.json in my files. 
It came and go. closing.
