### ISSUE TITLE
Action buttons missing in Party details

### ISSUE THREAD

**Issue by MilosStanic** [Urigo/meteor-angular-socially#21]
As in title... there are no save, reset, cancel, buttons in party-details.ng.html

**Comment by MilosStanic** [comment]
Also, both form fiels in the same file are called `Party Name`, the second one should be called `Party Details`

**Comment by MilosStanic** [comment]
Sorry, now I see that there is no need for these buttons.

**Comment by Urigo** [comment]
cool
