### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by mikepc** [Urigo/meteor-angular-socially#23]
This is a pretty dumb question, but I am new to Meteor, but I'm not new to Angular using Karma/Jasmine for unit testing Angular objects.

I'm really trying to get my head around exactly how to unit test an Angular-Meteor app. I know there are tutorials on the Roadmap, but without any boilerplate of how to get started, I'm utterly lost.

Is there anywhere I can find something that has samples of of a working test harness for an angular-meteor app?

**Comment by funkytaco** [comment]
:+1:

**Comment by Tallyb** [comment]
A sorrowful issue for all of meteor...

**Comment by Urigo** [comment]
Coming very soon!

**Comment by biomassives** [comment]
https://github.com/meteor-velocity/velocity-examples << check these unit test methods for meteor,  https://medium.com/angularjs-meetup-south-london/angular-unit-testing-with-jasmine-24795a44998e << jasmine unit testing for angular  :: good reference points for how unit testing can be set up. I"m working on it, and will share my results. :+1: )

**Comment by biomassives** [comment]
http://www.sitepoint.com/unit-testing-angularjs-services-controllers-providers << Angular testing where grunt-karma acts as a test runner for Jasmine. Meteor has Velocity as its testing framework, which uses Jasmine, so we should be able to get started with unit tests for both meteor and angular app features.  I am interested in improving my code process by adopting a BDD/TDD testing.

**Comment by Urigo** [comment]
@biomassives thanks, we are using Jasmine and Velocity for unit tests with this package:
https://github.com/Sanjo/meteor-jasmine

Do you want to write a blog post or tutorial about it?
maybe just add a few simple tests to the tutorial?

I would love to help with that

**Comment by funkytaco** [comment]
:+1:  I would love to see that

**Comment by dyaa** [comment]
@Urigo i'm so waiting for this.

**Comment by kamilkisiela** [comment]
The new tutorial brings unit-tests :) You can check it

**Comment by sean-stanley** [comment]
I don't see any unit tests in the client components for testing business logic. Just some tests on Meteor methods. An example using Ng-Mocks and Angular Meteor together would be really handy. 

Meteor.js has some great client unit test examples for blaze components. Something similar for angular components would be really appreciated.
