### ISSUE TITLE
Assigment 1: 3-Way data binding

### ISSUE THREAD

**Issue by idanwe** [Urigo/meteor-angular-socially#26]
Thanks for joining the university!

The start point is `step_00`. so, [make sure](http://angularjs.meteor.com/tutorial/step_00) you are ready to go.

We will start by structure our app: create `server`, `model` and `client` folders, and move the relevant files.
The assignment is to show list of parties. Create the necessary  Controller and Collection.
Add some dummy parties when the server loads if there aren't parties.

Fork branch `step_03_u` and open Pull Request with your solution.

Assignment due: 31/5

**Comment by Urigo** [comment]
Guys, where are you?
This is a great chance to learn angular-meteor with everyone and get all your questions and best practices unanswered!

**Comment by LookOnTheBrightSide** [comment]
Trying to follow the tut but I'm getting this :

```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
 WARNING: Tried to load angular more than once.
```

This is in step_00.

**Comment by ambujpunn** [comment]
@LookOnTheBrightSide try updating your packages `urigo:angular and meteor`

**Comment by biomassives** [comment]
interesting that the vision is to use a models folder. I"m working through this. thanks
