### ISSUE TITLE
directives example using templateUrl

### ISSUE THREAD

**Issue by funkytaco** [Urigo/meteor-angular-socially#28]
How do I keep meteor from turning a templateUrl for a directive into an HTML element. Shouldn't it just work, as long as I don't have an html tag in the directive file?

```
While building the application:
client/items/directives/myDirective.html:1: bad formatting in HTML template
```

I tried renaming it to myDirective.ng.html, and the app renders, but the directive isn't working with `templateUrl`. It works just fine with `template`.

```
.directive('myDirective', function () {
    return {
        //templateUrl: './myDirective.ng.html'
        template: '<ul><li>new directive here works</li></ul>'
    };
});
```

**Comment by funkytaco** [comment]
Of course I figure it out as soon as I post:

```
        templateUrl: 'client/items/directives/myDirective.ng.html'
```

I had to use a path to the file, but I don't know why.

I still have an outstanding question: when do I use the '.ng.html' suffix? Can I use it for any HTML I don't want rendered by Meteor?

**Comment by ambujpunn** [comment]
@funkytaco that's really funny you ran into that problem, because I'm running into a similar problem but I'm trying to add an ionicModal and using templateUrl to link to a relative path of the Modal but it seems like it cannot find it..hmm I think it largely is because of the structuring of our meteor-angular app. I wonder if such "items" or "custom items" need to be included in their directory

**Comment by ambujpunn** [comment]
OMG! it worked. for Ionic Modals, you have to specifically put them based on the structure such as: client/home/modals/my-modal.ng.html

**Comment by ambujpunn** [comment]
I'm sure this might be a trivial issue but I've been stuck on this for the past 2-3 weeks and being a noob in Meteor and Angular this has been really tough to figure out. Feels really nice to get this working. @Urigo I know you're working on a meteor-ionic tutorial, I would love to contribute on the doc as I've gotten some very good experience integrating these two technologies together.

**Comment by funkytaco** [comment]
Yeah, I expected my first templateURL path to work as it worked fine in Angular. I guess Meteor runs from the root directory path of the project.

**Comment by Urigo** [comment]
@ambujpunn I would love your help with the Ionic tutorial!
You can just pull request to a new branch or just contact me privately for help.
@funkytaco I'm happy you figured it out, now people can run into this issue when they will search for the same problem

**Comment by roeeyud** [comment]
Same issue happened to me, 
Fixed by adding the missing 'angular-meteor' in the app angular module dependencies.
