### ISSUE TITLE
Any recommendations for mongo tutorials?

### ISSUE THREAD

**Issue by funkytaco** [Urigo/meteor-angular-socially#29]
I'm picking up Meteor and Angular just fine, but looking at https://github.com/Urigo/meteor-angular-socially/blob/master/model/parties.js I realize I have more to learn about Mongo.

Looking at `parties.js`, I cannot figuire if `Parties.allow()` is a Mongo feature (i.e. `Mongo.collection.allow`), but I don't see that in the documentation here: http://docs.mongodb.org/manual/reference/method/js-collection/

I also don't see it here:
http://angular-meteor.com/api/AngularMeteorCollection

Any help would be great.

**Comment by Tallyb** [comment]
It is a meteor collection funciton - 
http://docs.meteor.com/#/full/allow

**Comment by funkytaco** [comment]
Great, thanks

**Comment by Urigo** [comment]
Thanks for the question and the answer.
I've added a link in the tutorial to better explain - https://github.com/Urigo/angular-meteor/commit/205b899474f2573e6f400e8536c3b41e6f85fdf9
