### ISSUE TITLE
meteor upgrade -> bootstrap package errors

### ISSUE THREAD

**Issue by aegor** [Urigo/meteor-angular-socially#3]
This is known issues:
https://github.com/Nemo64/meteor-bootstrap/issues/17

Use mizzao:bootstrap-3 package instead wit this patch:

diff --git a/client/styles/custom.bootstrap.import.less b/client/styles/custom.bootstrap.import.less
index 0539c79..0d99f42 100644
--- a/client/styles/custom.bootstrap.import.less
+++ b/client/styles/custom.bootstrap.import.less
@@ -11,6 +11,11 @@
 // Variables
 // --------------------------------------------------

+@link-hover-decoration: none;
+@cursor-disabled: true;
+@input-border-radius-small: 3px;
+@input-border-radius-large: 5px;
+@progress-border-radius: 1px;

 //== Colors
 //

**Comment by Urigo** [comment]
@aegor You should use the new official Bootstrap Meteor package
