### ISSUE TITLE
meteor-roles support?

### ISSUE THREAD

**Issue by harinanda** [Urigo/meteor-angular-socially#33]
meteor-roles support?

**Comment by Amalthean** [comment]
You can do it manually, for example, you can add simple _roles_ property to your _user_ document when you are creating the user, and then check for these roles in your _allow/deny_ rules when you are creating or updating docs.
You can also add a third-party package such as the deepwell:authorization package for example, which can be found on Atmosphere at http://atmospherejs.com/deepwell/authorization and which comes with a more complex role model.

**Comment by DAB0mB** [comment]
@harinanda You're more than welcome to submit a pull request and add this feature. We will be happy to have it! As for now this is not a part of our milestones.
