### ISSUE TITLE
ERROR whitelist rejection while running on ios

### ISSUE THREAD

**Issue by ambujpunn** [Urigo/meteor-angular-socially#34]
I'm having a hard time getting my app to have the same functionality that it has as a web app on an ios simulator. For one, the data is not the same (even though it is also being hosted on localhost) and when I trigger some sort of click event (clicking a button that does a check).. I see this error on xcode:

`ERROR whitelist rejection: url='http://localhost:3000/sockjs/info?cb=f4uguocgmc'`

What could be the cause of this? At one point, everything was working fine but recently I have not been able to test on iOS due to this problem. @Urigo or anyone else, any idea?

**Comment by ambujpunn** [comment]
When I go to that url, i get this result:

`{"websocket":true,"origins":["*:*"],"cookie_needed":false,"entropy":4273628293}`

**Comment by ambujpunn** [comment]
Seems like I don't have the cookie...why is this?

**Comment by ambujpunn** [comment]
@Urigo Any luck?

**Comment by ambujpunn** [comment]
I was able to get rid of the errors by adding `App.accessRule('*');` in my `mobile-config.js` recommended by this: http://stackoverflow.com/questions/29305109/meteor-js-cordova-error-error-whitelist-rejection. But for some reason I'm not able to see the same data on mobile as i see on my desktop browser.

**Comment by Urigo** [comment]
Hi @ambujpunn can you add this into the tutorial docs and the repo?
About not seeing the same data, can you share a repo

**Comment by ambujpunn** [comment]
Hi @Urigo, that change was actually able to fix the problem (after I re-ran meteor). I can add this into the doc as well. I'll submit a PR shortly.

**Comment by yumikohey** [comment]
@ambujpunn, i encountered into this issue, but i don't see the mobile-config.js file. Where is it? or we have to create ourselves?

**Comment by ambujpunn** [comment]
Hi Yumiko,

I tried to reply to your comment on github but it seems like it's been
removed. Either way, yes I created a mobile-config.js file

**Comment by Urigo** [comment]
@ambujpunn maybe you can add this to the docs?

**Comment by ambujpunn** [comment]
@Urigo Sent a PR for this

**Comment by Urigo** [comment]
Thanks @ambujpunn I've placed your notes inside the tutorial
