### ISSUE TITLE
Bad "step 1" link at https://angular-meteor.com/tutorial/step_00

### ISSUE THREAD

**Issue by ppotoplyak** [Urigo/meteor-angular-socially#36]
Screen shot attached.  I would push a PR but I am not sure where the source repo is.

thanks,
-pavel

![bad-link](https://cloud.githubusercontent.com/assets/4952152/8286756/0326836e-18d1-11e5-808d-5593d08e08d9.png)

**Comment by Urigo** [comment]
Thanks Pavel!
Fixed  (for PR look at the button on the top that say "improve this doc")
