### ISSUE TITLE
Step 12: Adding sort modifier on client Minimongo..why is it needed?

### ISSUE THREAD

**Issue by ambujpunn** [Urigo/meteor-angular-socially#42]
In Step 12 for pagination, it's stated to add the sort modifier to the client as well but why is the data not sorted when the server publishes it to the client? 

(`"That is because the sorting is not saved when the data is sent from the server to the client"`) <-- from the doc.

Understanding the reactivity part of Meteor I would assume that the server would publish the sorted data. I'm actually having a problem with this and it seems like the only way to get this working is to add the sort modifier on the client as well for the Minimongo. But shouldn't Minimongo look exactly like the data that the server publishes to the client? (aka Minimongo)

I've found some other SO posts (http://stackoverflow.com/questions/27664464/meteor-publish-function-is-not-re-run-after-inserting-an-item, http://stackoverflow.com/questions/26398952/meteor-publish-publish-collection-which-depends-on-other-collection) about this and it seems like reactivity joins haven't been fully solved by MDG yet (maybe we need one of us to let someone inside MDG know..hmmmm @Urigo :stuck_out_tongue_winking_eye: :smile: )

**Comment by alexanderzeillinger** [comment]
I agree, this needs some clarification.

**Comment by Urigo** [comment]
sooo with the new [Angular Meteor 1.3](info.meteor.com/blog/angular-meteor-1.3) there is no difference between how we do pagination then the rest of the Meteor community.
So this discussion is most fit in the [Meteor forums](forums.meteor.com), but I would love to continue that discussion with all the Meteor community

**Comment by alexanderzeillinger** [comment]
@ambujpunn I found this excellent Stackoverflow answer which made things a lot clearer for me: http://stackoverflow.com/a/21853298/757218
