### ISSUE TITLE
detect accounts-ui logout

### ISSUE THREAD

**Issue by funkytaco** [Urigo/meteor-angular-socially#45]
$stateChangeError doesn't seem to catch a logout. What should I be looking to implement to redirect to /home on logout?  I looked through the tutorial for this, but didn't see an answer.

**Comment by funkytaco** [comment]
I've been reading and search but most things I'm finding only relate to Meteor. 

I noticed in the doc there is a `$meteor.logout()` function, which I assume is fired by accounts-ui. I'd just like to watch this somehow so I can redirect to '/home'

**Comment by funkytaco** [comment]
To clarify, I'm doing this, but it only fires 'made it' on login, not logout:

```
    .state('accountChildren', {
        url: '/account/children',
        templateUrl: 'client/account/children/children.ng.html',
        controller: 'AccountChildrenCtrl',
        resolve: {
          "currentUser": ["$meteor", function($meteor){
             console.log('made it');
            return $meteor.requireUser();
        }]}
```

**Comment by funkytaco** [comment]
According to [this stackoverflow answer](http://stackoverflow.com/questions/25185974/detecting-logout-event-of-loginbuttons-in-meteor) there isn't a way to detect the account-ui logout via a callback.

So I guess for now, I can wrap my content in an ng-if checking for currentUser, like this:

```
<div ng-if="currentUser">currentUser: {{currentUser}}</div>
<div ng-if="!currentUser">Not logged in.</div>
```

I'd rather redirect to `/home` if anybody knows of a way to do that at the app-level, or I guess with a $scope.$watch() in a controller..

**Comment by Urigo** [comment]
you can $watch or you can use $scope.autorun,

$stateChange catches a state change, that's it's job, starting the redirection in another thing

**Comment by funkytaco** [comment]
Where is `currentUser` on the scope? I tried $rootScope and $scope.

**Comment by Urigo** [comment]
it's on $rootScope

**Comment by Urigo** [comment]
@funkytaco any news?
