### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by donedgardo** [Urigo/meteor-angular-socially#56]
Hello! I'm fairly new to meteor-angular.
In the [meteor-angular api docs](http://angular-meteor.com/api/auth)  it describes the meteors {{ currentUser}} = $rootScope.currentUser
But in the socially app @ client/index.html you use $root.currentUser instead of $rootScope.currentUser.
I ask because I'm having troubles in my app where $rootScope.currentUser.profile.name doesn't work all the time.
And maybe someone can enlighten me with the difference.

**Comment by Urigo** [comment]
Angular's way of calling `$rootScope` in the template is through `$root` - http://stackoverflow.com/a/23596034/1426570
