### ISSUE TITLE
Help with Meteor 1.2 Update

### ISSUE THREAD

**Issue by alexanderzeillinger** [Urigo/meteor-angular-socially#57]
As far as I understood from the tutorial we have to use ".ng.html" to avoid that Blaze interferes with AngularJS. With the Meteor 1.2 update we can now do

```
meteor remove blaze-html-templates
meteor add static-html
```

to remove Blaze and I thought I don't need to use ".ng.html" anymore.
Unfortunately this doesn't seem to be the true, why is that?

**Comment by Urigo** [comment]
@mxab what do you think about that?
now that we have those possibilities, we can improve the `angular-meteor-platform`

**Comment by mxab** [comment]
sounds interesting. I haven't looked into static-html/blaze-html-templates so far.
Leaving ng.html would then make sense for the index.html the rest still needs to be processed for the template cache right?
what happens if someone still wants to use blaze combined with angular or wants to migrate slowly from one to the other?

**Comment by Urigo** [comment]
We can give that functionality like today, but I want the default way to be without Blaze dependencies

**Comment by mxab** [comment]
I just tried adding the static-html@1.0.0 package to the angular-meteor-platform.

I get

```
   While selecting package versions:
   error: unknown package: isobuild:compiler-plugin
   Required by: ecmascript 0.1.3-plugins.5
   Required by: static-html 0.0.2-plugins.0

   unknown package: isobuild:isopack-2
   Required by: caching-compiler 1.0.0-plugins.1
   Required by: templating-tools 0.0.2-plugins.0
   Required by: caching-html-compiler 1.0.1-plugins.0
```

I guess all this stuff will be available with the release of 1.2 or is there anything I missed?

**Comment by Urigo** [comment]
yes you have to use the RC version

**Comment by mxab** [comment]
With the chance of sounding dump, what exactly is the current rc version string? I cannot find it :(

**Comment by Urigo** [comment]
I believe we are at `meteor update --release METEOR@1.2-rc.12` right now

**Comment by mxab** [comment]
Ok I'm testing the 1.2 with static files locally, but so far I cannot say much as 1.2 breaks a lot of stuff

**Comment by mxab** [comment]
@Urigo 
I'm having a index.html but for some reason it still generates a template.index.js besides the markup that is initially there

**Comment by mxab** [comment]
Ok there seems to be a strange issue if I put attributes to the body tag, if use them in a child element of body everything is fine again

Here is a initial sample
https://github.com/mxab/meteor-ng-app

**Comment by Urigo** [comment]
That's strange.
This feature was added to Meteor here:
https://github.com/meteor/meteor/pull/3467

And I've just looked at the code for `static-html` and it looks like it exists:
https://github.com/meteor/meteor/blob/devel/packages/static-html/static-html.js#L70

Can you debug and confirm there is a bug in the way Meteor is adding the `Body` attribute or is it something else?

**Comment by mxab** [comment]
If I just move the ng-app attr up like this
https://github.com/mxab/meteor-ng-app/compare/attr_on_body

I get this result
<img width="939" alt="screen shot 2015-09-14 at 09 07 35" src="https://cloud.githubusercontent.com/assets/1607547/9844026/27ad54a2-5ac0-11e5-833b-db88852f6bed.png">

**Comment by mxab** [comment]
Ok I reported the issue for here
https://github.com/meteor/meteor/issues/5223

**Comment by mxab** [comment]
ok I released a new version of the angular-meteor-platform (0.0.2) that comes with static-html looks good so far, I also updated the sample app
https://github.com/mxab/meteor-ng-app

I would release the 1.0 version when  meteor angular 1.0 is released

**Comment by Urigo** [comment]
Hi @alexanderzeillinger @mxab I'm about to release `angular@1.2.0` and want your feedback:
`meteor remove blaze-html-templates`
`meteor remove ecmascript`
`meteor add angular@1.2.0-rc.5`

**Comment by mxab** [comment]
I'm working on it and let you know

**Comment by mxab** [comment]
Initial smoke test looks good sofar

**Comment by Urigo** [comment]
The new tutorial with `angular@1.2.0` now shows how to remove Blaze and include only Angular
