### ISSUE TITLE
Step 5: Routing with Angular-UI-Router and Bower

### ISSUE THREAD

**Issue by jordangarside** [Urigo/meteor-angular-socially#6]
```
Uncaught Error: [$injector:modulerr] Failed to instantiate module inlet due to:
ReferenceError: UiRouter is not defined
    at http://localhost:3000/client/cordova/lib/project.litcoffee.js?2a52e2448fe103ca98771bff32bac8a2c27763cf:17:17
    at Object.invoke (http://localhost:3000/packages/urigo_angular.js?a2c8465c9129380d59e25bfb536d3983b45ecbf2:4211:17)
```

I used to be able to use Meteor templates with `UiRouter.template("templateName")`, in 0.6 it is suggested to use _.tpl_ files, but then I have to keep track of file paths and can't use meteor helpers anymore.
Is there any way to use Meteor templates still?

**Comment by Urigo** [comment]
All templates exists in $templateCache, you can recover them from there like you would in a regular Angular application

**Comment by Urigo** [comment]
@jordangarside fixed.  please re-open in case of a problem
