### ISSUE TITLE
error loc.go not a function in route.js

### ISSUE THREAD

**Issue by francis-barban** [Urigo/meteor-angular-socially#60]
Do you know where the problem is? Thanks

angular.module("socially").run(["$rootScope", '$location', function($rootScope, $loc) {
  $rootScope.$on("$stateChangeError", function(event, toState, toParams, fromState, fromParams, error)  {
    // We can catch the error thrown when the $requireUser promise is rejected
    // and redirect the user back to the main page
//    if (error === "AUTH_REQUIRED") {
    if (error) {
      $loc.go("/parties");
    }
  });
}]);

**Comment by Urigo** [comment]
Thank you so much for the feedback @francis-barban !
Fixed and deployed.
Sorry for the long delay
