### ISSUE TITLE
remove bootstrap in packages file

### ISSUE THREAD

**Issue by nhducit** [Urigo/meteor-angular-socially#63]
in step 18, bootstrap was removed but packages file still have twbs:bootstrap@3.3.5
http://angular-meteor.com/tutorials/angular1/angular-material-and-custom-angular-auth-forms

```
meteor-platform
urigo:angular
...
twbs:bootstrap@3.3.5
...
```

**Comment by Urigo** [comment]
@nhducit  thanks for the valuable feedback!
Fixed, pushed and deployed - https://github.com/Urigo/angular-meteor/commit/96a4b9bac8f8fb247627f98b61773435d2f7b00f
Sorry for the long delay

**Comment by nhducit** [comment]
@Urigo You're welcome :)
