### ISSUE TITLE
Step 6 - Bind one object

### ISSUE THREAD

**Issue by steveperx** [Urigo/meteor-angular-socially#64]
In this step, following your tutorial to the letter, I find that there seems to be a bug in the meteorObject.save() code... or at least, it doesn't behave as if I would expect.

If I pull up a Party details page, but make no changes to the details and hit the Save button, it overwrites the name and description of the Party object with empty strings The text in the `<input>` boxes disappears indicating the Party object has no text in the name and description properties. This change is persisted to the server, and returning to the Parties List page sows that party with a blank title and a blank description.

Is this the expected behavior? I note that if I DO make changes to the data in the textboxes, everything seems to work fine. I haven't dug into the angular-meteor source code for meteorObject, but I suspect this has something to do with the save() method?

Here is the code I'm using (should be exactly your code in the tutorial):
#### PartyDetailsCtrl

``` javascript
angular.module("socially").controller("PartyDetailsCtrl", ['$scope', '$stateParams', '$meteor', function($scope, $stateParams, $meteor){

      $scope.party = $meteor.object(Parties, $stateParams.partyId, false);

      $scope.save = function() {
        $scope.party.save()
          .then(function(numberOfDocs){
            console.log('save success doc affected ', numberOfDocs);
        })
          .catch(function(error){
            console.log('save error', error);
        });
      };

      $scope.reset = function() {
        $scope.party.reset();
      };

    }]);
```
#### party-details.ng.html

``` javascript
Here you will see the details of the party:

<input ng-model="party.name">
<input ng-model="party.description">

<button ng-click="save()">Save</button>
<button ng-click="reset()">Reset form</button>
<button ui-sref="parties">Cancel</button>
```

**Comment by Urigo** [comment]
@steveperx can you please update your `angular` package to `angular@1.0.0-rc.11` and let me know if that helped

**Comment by Urigo** [comment]
With the new `helpers` API in angular-meteor 1.3, we don't use $meteorObject anymore
