### ISSUE TITLE
Strange output in Step 03 Demo 

### ISSUE THREAD

**Issue by horaceho** [Urigo/meteor-angular-socially#74]
Is the output from  http://socially-step03.meteor.com/  OK?

It shows:

![step3](https://cloud.githubusercontent.com/assets/6657/10603186/31b78502-774f-11e5-9ed9-cc1b9e62bfa7.png)

**Comment by dotansimha** [comment]
@horaceho 
Hi
The deployed version is not up-to-date at the moment, will update is soon!

**Comment by Urigo** [comment]
@dotansimha it looks like something in the database, I think we need to reset it

**Comment by dotansimha** [comment]
Hi @horaceho @Urigo 
Fixed it.

A note about DB reset: 
If you run on a local computer, just run: 
`
meteor reset
`

But if you deployed your app, you can use:
`
meteor deploy my-website.meteor.com --delete
meteor deploy my-website.meteor.com
`

**Comment by horaceho** [comment]
👍
