### ISSUE TITLE
Step 5.8: Duplication of Parties collection

### ISSUE THREAD

**Issue by marvinmarnold** [Urigo/meteor-angular-socially#79]
Why does a client side Parties DB [need to be instantiated](https://github.com/Urigo/meteor-angular-socially/commit/ac842f278185168496eb0b13883c7ba848fca7e9) if if is already available from server.js?

**Comment by Urigo** [comment]
That's the only place it's instantiated.
On the server we just insert documents into it, we don't declare it

**Comment by marvinmarnold** [comment]
The exact same line of code (declaration)

```
Parties = new Mongo.Collection("parties");
```

exists on lines 1 of both [server.js](https://github.com/Urigo/meteor-angular-socially/blob/ac842f278185168496eb0b13883c7ba848fca7e9/server.js#L=1) & [app.ng.js](https://github.com/Urigo/meteor-angular-socially/blob/ac842f278185168496eb0b13883c7ba848fca7e9/app.ng.js#L=1). Both files are in the root directory and aren't in Meteor.isClient/Server clauses so I still think it is being instantiated twice on both client & server.

**Comment by Urigo** [comment]
ohhh you are right!

It's a mistake, will fix soon

**Comment by marvinmarnold** [comment]
thanks @Urigo awesome tutorials, helping me a lot as a total angular noob

**Comment by dotansimha** [comment]
Thanks @marvinmarnold,
just fixed it!
