### ISSUE TITLE
autopublish is not working correctly with angular@1.0.5

### ISSUE THREAD

**Issue by wapacz** [Urigo/meteor-angular-socially#83]
I was going through the tutorial: http://angular-meteor.com/tutorials/angular1/folder-structure
And noticed problem with Mongo and Collection - after adding document to database directly (CLI, RoboMongo) or with web app all document data are cleared - only _id lefts.

Somehow I was able to add angular@1.0.5 with: 'meteor add angular' command.
I've found that when I downgrade to angular to 1.0.4 version it start working again, so there must be some bug with it in 1.0.5.

**Comment by wapacz** [comment]
I've opened the same one for angular-meteor: https://github.com/Urigo/angular-meteor/issues/830,
since I'm not sure where the problem is.

**Comment by Urigo** [comment]
Issue fixed
