### ISSUE TITLE
Step 7.5 error

### ISSUE THREAD

**Issue by alexanderzeillinger** [Urigo/meteor-angular-socially#84]
See my comment from August here https://github.com/Urigo/meteor-angular-socially/commit/6d3bd492fb049a55bf03eae777c6d0d77dc3e0d2#commitcomment-12941551

Also still there in step 9.3 and 12.2, 12.3, 12.4, 12.10.

**Comment by Urigo** [comment]
@alexanderzeillinger should be fixed now
