### ISSUE TITLE
Using === instead of == in server/parties.js breaks app

### ISSUE THREAD

**Issue by mackbrowne** [Urigo/meteor-angular-socially#85]
I'm trying to use eslint, it wants me to change the following in server/parties.js from 

``` javascript
  if (searchString == null)
```

to

``` javascript
 if (searchString === null)
```

Going to party details gives me a nasty looping error and breaks working functionality in angular that seems to have no relation.

> Error: MinimongoError: Mod on _id not allowed [409]

Pretty sure this is a bug.  Changing back to == fixes everything.

**Comment by Urigo** [comment]
@mackbrowne Please try to change your solution to the new [1.3 API](http://info.meteor.com/blog/angular-meteor-1.3).   you can check out the same chapter on the tutorial, it is now updated.
then it will be easier to know if it's a Meteor problem or an Angular Meteor problem

**Comment by mackbrowne** [comment]
Hi @Urigo , same behaviour in 1.3.  Im not familiar enough with the differences between == and === but I can personally say I haven't seen anything remotely like this error in any of my larger 'pure meteor' project.

One thing i noticed while playing around with the chrome console. 

```
'' == null
//empty string returns true
```

and 

```
'' === null
//empty string returns false
```

This behaviour could be what is causing the problem.  Perhaps its not a bug, but just bad practice?  An easy workaround would be to use, although I'm not sure if this could be considered bad practice?

```
if( !searchstring )
```

**Comment by Urigo** [comment]
@mackbrowne in the new tutorial we use if `(!searchString || searchString == null) {` and it works the same also if you do if `(!searchString || searchString === null) {`
If also changed it to  `(searchString === null) {` and  `(searchString == null) {` and everything works fine.
I've used the end result of step 12 - https://github.com/Urigo/meteor-angular-socially/archive/step_12.zip

Please let me know if it still doesn't work for you and please share a reproduction

**Comment by Urigo** [comment]
Closing now but feel free to re-open if it doesn't work for you
