### ISSUE TITLE
templateUrl - html cached?

### ISSUE THREAD

**Issue by Guro** [Urigo/meteor-angular-socially#87]
Hi i'm following angular-meteor tutorial on official site but have encountered strange problem:
i have some component which has templateUrl: 'client/boards-form/form.html'
changing form.html template does not take effect, if i would change path to a different file i.e form2.html
it will render new template once but afterwards no changes that was made to the file will be reflected on actual app.

Can someone suggest what could cause it? tried meteor reset but it does't help
Thanks

**Comment by dotansimha** [comment]
Which version do you use? can you provide your `.meteor/versions` file?

**Comment by Guro** [comment]
http://pastebin.com/EJmtz7gH

**Comment by Guro** [comment]
any suggestions what could be wrong?

**Comment by Guro** [comment]
Additional info: just downloaded source of:
**meteor-angular2.0-socially-step_04**
same problem occurs.

as i'm seeing that happens only for external HTML specified by templateUrl, if i change to `template:'<b>inline template </b>'` then everything works perfectly

**Comment by Urigo** [comment]
@Guro this is a Socially 2.0 problem, can you please open this issue here? https://github.com/Urigo/meteor-angular2.0-socially
