### ISSUE TITLE
step 12 memory leak

### ISSUE THREAD

**Issue by jmwierzbicki** [Urigo/meteor-angular-socially#88]
I found out during production of my application that :

``` javascript

  $scope.parties = $meteor.collection(function() {
    return Parties.find({}, {
      sort : $scope.getReactively('sort')
    });
  });

```

causes memory leak when app state changes because it doesnt stop collection when state changes there is $scope.meteorCollection alternative that address this issue, but is never used and detailed in tutorial?

**Comment by Urigo** [comment]
@jmwierzbicki that's for the heads up.
With the new [1.3 release](http://info.meteor.com/blog/angular-meteor-1.3) we use the `helpers` syntax and we stop each autorun when the scope destroys.
Check out the [updated chapter 12](http://www.angular-meteor.com/tutorials/socially/angular1/search-sort-pagination-and-reactive-vars) and let me know if it's better

**Comment by jmwierzbicki** [comment]
well, hate helpers syntax, and my application broke after update because my paginated list, when changed state doesn't show results - but it does when i force refresh page  (until i switch state again) ;) I'm starting to rewriting whole code now.

**Comment by Urigo** [comment]
@jmwierzbicki if you can share your code I can have a look and help
