### ISSUE TITLE
No display at all after 23.9

### ISSUE THREAD

**Issue by elmor34** [Urigo/meteor-angular-socially#91]
No display at all

Uncaught TypeError: LocalInjectables is not a function(anonymous function) @ parties-list.component.js:17(anonymous function) @ parties-list.component.js:18(anonymous function) @ parties-list.component.js:18
socially.component.js:14 Uncaught TypeError: MeteorReactive is not a function(anonymous function) @ socially.component.js:14(anonymous function) @ socially.component.js:15(anonymous function) @ socially.component.js:15
angular-meteor-user.js:85 [angular-meteor.$rootScope.currentUser/loggingIn] Please note that this functionality has migrated to a separate package and will be deprecated in 1.4.0.  For more info: http://www.angular-meteor.com/api/1.3.0/auth
sw-toolbox.js:20Uncaught (in promise) TypeError: Request scheme 'chrome-extension' is unsupported(…)
sw-toolbox.js:20Uncaught (in promise) TypeError: Request scheme 'chrome-extension' is unsupported(…)
content.js:1 Resource interpreted as Stylesheet but transferred with MIME type text/plain: "chrome-extension://annopcfmbiofommjmcmcfmhklhgbhkce/css/frames.css".g @ content.js:1(anonymous function) @ content.js:1(anonymous function) @ content.js:1
sw-import.js?baseURI=http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fpla…2Fbootstrap%2Fsw-toolbox-setup.js&precache=&skipWaiting=true&version=1.0:1 GET http://localhost:3000/sw-import.js?baseURI=http%3A%2F%2Flocalhost%3A3000%2F…w%2Fbootstrap%2Fsw-toolbox-setup.js&precache=&skipWaiting=true&version=1.0 net::ERR_INSECURE_RESPONSE

**Comment by dotansimha** [comment]
Hi @elmor34 
Step 23 is still not in producation, because we wait for a change in angular2-now in order to provide full support and annotations for Angular-Meteor.

**Comment by elmor34** [comment]
No output on browser. with later updates I get 

> Error logging in with token: Error: You've been logged out by the server. Please log in again. [403]
> parties-list.component.js:229 Uncaught TypeError: LocalInjectables is not a function
> socially.component.js:42 Uncaught TypeError: MeteorReactive is not a function
> angular-meteor-data.js:1227 [angular-meteor.$rootScope.currentUser/loggingIn] Please note that this functionality has migrated to a separate package and will be deprecated in 1.4.0.  For more info: http://www.angular-meteor.com/api/1.3.0/auth
> http://localhost:3002/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by DAB0mB** [comment]
@elmor34 As for now there is the problem with the final step 23, we're working to fix it in the upcoming days as for now you can checkout step 22 which works just fine

**Comment by Urigo** [comment]
fixed and deployed.
@elmor34 please open a new issue if the problem persists, thank you!
