### ISSUE TITLE
iOS Not Working on Port !== 3000

### ISSUE THREAD

**Issue by jboothe** [Urigo/meteor-angular-socially#94]
_From @jboothe on January 1, 2016 18:36_

Although the angular 1 socially app works properly in the browser, I ran into a strange issue where only part of the app shows in iOS/Android emulator when running meteor on any port other than the default 3000.  

For instance, running the following, results in the _Sign in_ and _Parties List_ portions not showing on iOS:
`meteor run ios --port 3031`

This is easily replicated. Pull down step 12 zip file, then:

```
meteor add-platform ios
meteor run ios --port 3031
```

_BTW I tried several ports with the same results_
## App on Port 3000

`meteor run ios`

![meteor-on-port-3000](https://cloud.githubusercontent.com/assets/3723481/12071745/f12a28f4-b089-11e5-95fc-21a2d13394fd.png)
## App on Port 3031

`meteor run ios --port 3031`

![meteor-on-port-3031](https://cloud.githubusercontent.com/assets/3723481/12071777/a9fff5e2-b08b-11e5-9029-9607aec9a739.png)

_Copied from original issue: Urigo/angular-meteor#1054_

**Comment by dotansimha** [comment]
@jboothe 
I think you should specify `--mobile-server` to meteor, for example:

```
meteor run ios --mobile-server localhost:3031
```

**Comment by jboothe** [comment]
That did the trick. Thanks.

**Comment by jboothe** [comment]
I spoke too soon. When I started that app using your command I saw it work correctly in the emulator and thought we had a score. Looking at the terminal output, it actually runs on port 3000. :/

```
$ meteor run ios --mobile-server localhost:3031
[[[[[ ~/Sites/_Projects/Angular-Meteor/Angular1/socially ]]]]]

=> Started proxy.
=> Started MongoDB.

WARNING: It looks like you are using OAuth2 login in your app. Meteor's OAuth2 implementation does not currently work with mobile apps in local development mode, except in the iOS simulator. You can run the iOS simulator with 'meteor run ios'. For additional workarounds, see https://github.com/meteor/meteor/wiki/OAuth-for-mobile-Meteor-clients.
=> Started your app.
=> App running at: http://localhost:3000/
=> Started app on iOS Simulator.
```

So I tried a couple variations of your suggestion and the emulator shows only the search box and sort drop down: 

```
meteor run ios --mobile-server localhost --port 3031
meteor run ios --mobile-server localhost:3031 --port 3031
```

Both result in this:
NOTE: This is based on completion thru step_17.

![socially-partial-ios](https://cloud.githubusercontent.com/assets/3723481/12104203/28e93dcc-b317-11e5-8c84-bf604055af83.png)

**Comment by kamilkisiela** [comment]
There is now a new tutorial. Please reopen if necessary.
