### ISSUE TITLE
How do you run this...

### ISSUE THREAD

**Issue by elmor34** [Urigo/meteor-angular-socially#97]
When I try I get following messages with nothing on screen...
Is there anybody who succeeds on running this?

> Uncaught TypeError: LocalInjectables is not a function
> socially.component.js:42 Uncaught TypeError: MeteorReactive is not a function
> angular-meteor-data.js:1227 [angular-meteor.$rootScope.currentUser/loggingIn] Please note that this functionality has migrated to a separate package and will be deprecated in 1.4.0.  For more info: http://www.angular-meteor.com/api/1.3.0/auth

**Comment by ozsay** [comment]
the version of `angular2-now` is not correct.

Until it is fixed. In the meantime, you can just update it to the latest version.
